### ISSUE TITLE
sincedb_path handling

### ISSUE THREAD

**Issue by pazoozooCH** [docker-library/logstash#10]
I've noticed some problems with the sincedb handling for file parsing: By default, Logstash will try to store it's sincedb-file in the $HOME directory. In this image, this will be evaluated to _/root_, but Logstash runs as user _logstash_ and will not have permissions to save in this folder.

Another problem is that the sincedb file will be lost if the container is removed (e.g. with a version update). Obviously, this can be solved using volume mounting or a data container. Maybe it would be possible to change the $HOME directory for the logstash user and declare it as a volume in the Dockerfile at the same time?

**Comment by yosifkit** [comment]
So, `$HOME` should be working correctly since #12.  Would something like https://github.com/docker-library/elasticsearch/pull/77 be helpful to allow you to specify any non-root user and group to run as, using the `--user` flag on `docker run`?

**Comment by tianon** [comment]
Given that #11 is tracking the ability to run as a different user easily and that the `HOME` issue described here is fixed, I'm closing this one. :+1:
