### ISSUE TITLE
Logstash "Docker Official" base image

### ISSUE THREAD

**Issue by mgreau** [docker-library/logstash#110]
Hi @tianon @yosifkit 

As you know the Elastic Logstash "Docker Official" container image is based [on `ubuntu`](https://github.com/elastic/dockerfiles/blob/8.11/logstash/Dockerfile#L2).

I have two quick questions related to updating this base image:
1- Can you please confirm that moving from `ubuntu` to an `ubi` base image would not be a problem for this workflow?
2- Could you point me to the list of supported and non-supported base images for "Docker Official" images please?

Thanks

**Comment by tianon** [comment]
Moving to UBI should be fine as long as it's one of:

- `FROM redhat/ubi9`
- `FROM redhat/ubi9-minimal`
- `FROM redhat/ubi8`
- `FROM redhat/ubi8-minimal`

(see https://github.com/docker-library/official-images/pull/13908)

Generally, the "list" is any other supported image in the program (with the notable exceptions of the above-listed UBI images and a handful of Windows images: `mcr.microsoft.com/windows/{servercore,nanoserver}:{ltsc2022,1809}`).

**Comment by mgreau** [comment]
Thanks
