### ISSUE TITLE
Support custom shell script during setup (or list of plugins to be installed)

### ISSUE THREAD

**Issue by JannKleen** [docker-library/logstash#22]
Community-maintained plugins (e.g. https://www.elastic.co/guide/en/logstash/current/plugins-inputs-heroku.html) seem to be missing. It would be nice to have a way of installing them without creating our own repo

**Comment by yosifkit** [comment]
How about this?

``` console
docker run -d logstash bash -c "plugin install logstash-input-heroku && exec logstash -e 'input { stdin { } } output { stdout { } }'"
```

**Comment by JannKleen** [comment]
it increases the startup time quite a bit (also as the heroku plugin is not working right now i have to compile it myself), but this would certainly work ...

**Comment by md5** [comment]
@JannKleen I think @yosifkit was just suggesting that as a test. You should be able to run the `plugin install` command and whatever is needed to compile the plugin at build time in a derived `Dockerfile` instead and avoid any impact on startup time:

``` Dockerfile
FROM logstash
RUN # some commands to compile logstash-input-heroku
RUN plugin install logstash-input-heroku
```

**Comment by JannKleen** [comment]
yes that definitely works (sorry for being a bit slow understanding it before)
