### ISSUE TITLE
Allow for mounting configs through volume

### ISSUE THREAD

**Issue by xrl** [docker-library/logstash#23]
I would like to use this logstash because it uses java 1.8 and is "official" but the more popular alternative Dockerfile https://github.com/pblittle/docker-logstash allows a convenient folder mounting for configuration. Can we get the volume configuration behavior in this container?

**Comment by yosifkit** [comment]
A defined `VOLUME` is not necessary for mounting in a config. Since every logstash configuration will be different, the docs for [logstash](https://hub.docker.com/_/logstash/#start-logstash-with-configuration-file) already have an example of running with a custom config: `$ docker run -it --rm -v "$PWD":/config-dir logstash logstash -f /config-dir/logstash.conf`

**Comment by xrl** [comment]
Ah, I thought that command was ONLY for providing on .conf file. I was trying to get it run off a directory so I could coordinate through ansible. My issue with ansible is I do not know how to change the run command when starting the container.

**Comment by yosifkit** [comment]
If one conf includes the others, it should work fine.  I don't use ansible, so I can't help there.

**Comment by rodrigo-fagundes** [comment]
I'm trying to add the configuration via docker-compose, with no success. Do you know a way to add the -f option in compose?

I think the volume parameter is a good way out.

**Comment by yosifkit** [comment]
@rmfagundes, in docker-compose you just do `command: -f /config-dir/logstash.conf`  (no need for the extra `logstash` since the entrypoint script will [detect that](https://github.com/docker-library/logstash/blob/master/docker-entrypoint.sh#L6-L8).

**Comment by rodrigo-fagundes** [comment]
Thanks a lot.

**Comment by ianwalter** [comment]
Just wanted to note that AWS Elastic Beanstalk doesn't allow you to specify the command outside of the image, so unfortunately for Logstash you'd have to create your own image that inherits from Logstash in order to specify the config file.

**Comment by mi-hol** [comment]
@xrl @yosifkit @ianwalter @tianon could/should this be closed?

**Comment by tianon** [comment]
Indeed, thanks. :+1:
