### ISSUE TITLE
No output when using default example

### ISSUE THREAD

**Issue by semolex** [docker-library/logstash#25]
There is no usual STDOUT output from running example.
Just "Logstash startup completed".

`$ docker run -it --rm -v "$PWD":/config-dir logstash logstash -f /config-dir/logstash.conf`
Documentation is very important for such things.

**Comment by yosifkit** [comment]
That sounds right; unless you configure it with something like `output { stdout { } }` then logstash would not be outputting any logging to `STDOUT`.  The previous example in the [docs](https://hub.docker.com/_/logstash/#start-logstash-with-commandline-configuration) showed this.

**Comment by semolex** [comment]
Yeah, it is not a bug, but lack of documentation. If it is not necessary , I will close ticket.
Thanks.

**Comment by tianon** [comment]
The documentation has since been updated with better examples IMO. :smile:

**Comment by tianon** [comment]
Oh, perhaps not _specifically_, but the first example is now one that explicitly configures `stdout` as a logger, so I think it _is_ more clear now. :+1:

**Comment by tianon** [comment]
(specifically https://github.com/docker-library/docs/blob/2296da188d66951b6b59fcf462ebe4d70b0ffa36/logstash/content.md#how-to-use-this-image)

> ``` console
> $ docker run -it --rm logstash logstash -e 'input { stdin { } } output { stdout { } }'
> ```
