### ISSUE TITLE
To APT or To Bin

### ISSUE THREAD

**Issue by tianon** [docker-library/logstash#3]
See discussion on https://github.com/docker-library/official-images/pull/530 for more context.

In a nutshell, it's still an open debate as to whether upstream would officially prefer we use the binaries or the debs or the APT repo.

**Comment by md5** [comment]
I don't have any contacts in the Logstash or Elasticsearch projects, but it might be worth asking them to clarify the public documentation (or become involved in maintaining the `logstash` Docker image).

**Update**: I asked in `#logstash` on Freenode.

**Comment by markwalkom** [comment]
I'll ask the LS team and get back to you.

**Comment by md5** [comment]
One point in favor of using the debs is that they probably aren't running as `root` :stuck_out_tongue_winking_eye:

**Comment by md5** [comment]
Thanks @markwalkom!

**Comment by torrancew** [comment]
I'm not a Logstash team member, but I suspect that they'd recommend the debs/apt repos, for reasons mentioned by @md5

**Comment by md5** [comment]
@torrancew I haven't actually checked if the debs have a way to run other than `start-stop-daemon` that knows how to drop privileges, so it may not be that simple.

**Comment by torrancew** [comment]
@md5 this is a very good point

**Comment by yosifkit** [comment]
Just in case someone here misses this comment: https://github.com/docker-library/official-images/pull/530#issuecomment-77283315

**Comment by md5** [comment]
I looked into the "run as root" issue a little bit and it looks like the Debian/Ubuntu package relies on Upstart to do a `setuid` and `setgid` to user `logstash`. It then does an exec of `/opt/logstash/bin/logstash` (the same script used as the `CMD` in this iamge).

So it looks like this image will probably need to add `gosu` and an entrypoint to be able to run as `logstash`, assuming that's desirable.

**Comment by markwalkom** [comment]
We had a bit of a chat internally and we'd suggest using the deb as it provides consistency.

**Comment by tianon** [comment]
@markwalkom cool, thanks for chiming in and getting involved! :heart::heart:

By "the deb" -- would you prefer we grab that from the downloads page, or from the APT repo? (http://packages.elasticsearch.org/logstash/1.4/debian vs https://download.elasticsearch.org/logstash/logstash/packages/debian/logstash_1.4.2-1-2c0f5a1_all.deb)

**Comment by markwalkom** [comment]
That'd be your call.

I'd personally say the repo as you always get the latest version of that release, but if you want to package things then an included .deb should be fine.

**Comment by tianon** [comment]
@markwalkom awesome, thanks :heart:

@Moghedrin @md5 I was originally thinking the APT repo for consistency and `Dockerfile` simplicity, but for the repeatability aspects I'm wondering if maybe consuming the `.deb` directly would be better; thoughts?

**Comment by md5** [comment]
I'd probably use the Apt repo, since I'm assuming you'll still have to call `apt-get install` to pull in the dependencies of the `logstash*.deb`. That is, something like this:

```
RUN curl -o logstash.deb -SL $LOGSTASH_DOWNLOAD_URL \
        && dpkg --force-depends -i logstash.deb \
        && apt-get update \
        && apt-get -y install -f --no-install-recommends \
        && rm -rf /var/lib/apt/lists/* logstash.deb
```

I'd also stick with the Apt install since it makes using the GPG signature implied instead of having to do it explicitly.

**Comment by tianon** [comment]
True, fair enough.  It also looks like they keep multiple versions in the repo. :+1:

``` console
$ curl -sSL 'http://packages.elasticsearch.org/logstash/1.4/debian/dists/stable/main/binary-amd64/Packages' | awk -F ': *' '$1 == "Package" { pkg = $2 } pkg == "logstash" && $1 == "Version" { print $2 }'
1.4.1-1-bd507eb
1.4.0-1-c82dc09
1.4.2-1-2c0f5a1
```

**Comment by yosifkit** [comment]
> ```
> Depends: java7-runtime-headless | java6-runtime-headless | j2re1.7
> ```

So, `FROM java:7-jre` or `FROM debian`?

**Comment by md5** [comment]
As I said in https://github.com/docker-library/elasticsearch/pull/4#issuecomment-77601293, I think the Java-based images should generally be `FROM java:7-jre` to make sure they pick up any security updates in a timely fashion.
