### ISSUE TITLE
How to pass config when running Docker on Windows 

### ISSUE THREAD

**Issue by mobcdi** [docker-library/logstash#34]
Could you provide an example in the documentation about how you pass a config file to the logstash container when the container is hosted on a windows machine?

**Comment by tianon** [comment]
I definitely agree that it would be good to add more verbosity to our current docs (https://github.com/docker-library/docs/blob/master/logstash/content.md) -- perhaps an example after that bind-mount that explains using a `Dockerfile` to `COPY` and bake a configuration file into the image itself? (which is much more likely to work properly in Windows, and is probably more appropriate for a production deployment as well)
