### ISSUE TITLE
Startup and shutdown

### ISSUE THREAD

**Issue by matteoturra** [docker-library/logstash#39]
When I run 

```
docker run -it --rm --name logstash -v "$PWD"/config-dir:/config-dir logstash logstash -f /config-dir/$LOGSTASH_CONF_FILE
```

The container start and stop after a while without any message:

```
Settings: Default pipeline workers: 4
Logstash startup completed
Logstash shutdown completed
```

Why?

**Comment by michaelkrog** [comment]
Having the same issue

**Comment by tianon** [comment]
Is your configuration something you could share?  I'm not sure what could be causing this. :disappointed:

**Comment by bxu-mmd** [comment]
how do i run this container in AWS ECS. It exits out of the container as if i ran "docker run logstash logstash agent". How do i keep the process running?

{:timestamp=>"2016-04-27T02:16:47.014000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-04-27T02:16:47.123000+0000", :message=>"Pipeline main has been shutdown"}
{:timestamp=>"2016-04-27T02:16:50.026000+0000", :message=>"stopping pipeline", :id=>"main"}

**Comment by javifr** [comment]
Having the same issue also.
@tianon the thing is that even with an empty config the machine should keep going, and is not the case.
Someone could help here?

Thanks!

**Comment by bxu-mmd** [comment]
create a new dockerfile

FROM logstash:2.3.1-1
WORKDIR /etc/logstash
COPY config ./conf.d
CMD ["logstash","agent","-f","/etc/logstash/conf.d/"]

**Comment by cyounkins** [comment]
This appears to happen to me when a TTY isn't allocated. Running with `-t` fixes it.

**Comment by mi-hol** [comment]
@michaelkrog @javifr @matteoturra does the suggestion ' Run with -t fixes it.' work for you?

**Comment by mi-hol** [comment]
@tianon this seems no longer an issue :)

**Comment by tianon** [comment]
:+1:

**Comment by flowl** [comment]
Issue is still the same in 2019 with the ELK Dockerstack 7.4.2:

[2019-12-03T10:48:06,196][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2019-12-03T10:48:06,976][INFO ][logstash.javapipeline    ] Pipeline terminated {"pipeline.id"=>".monitoring-logstash"}
[2019-12-03T10:48:07,563][INFO ][logstash.runner          ] Logstash shut down.
