### ISSUE TITLE
Logstash 2.3.1/2.2.4

### ISSUE THREAD

**Issue by tegud** [docker-library/logstash#44]
Major backwards compatibility issues were found in Logstash 2.3, Logstash themselves recommend upgrading to 2.3.1/2.2.4 as quickly as possible - can we get the Official Docker Image updated to this version?

https://www.elastic.co/blog/logstash-2.3.1-and-2.2.4-released

Thanks

**Comment by tegud** [comment]
Just seen there's already an Open PR for this: #43

**Comment by 7AC** [comment]
#43 merged but the tags are not available yet

```
Tag 2.3.1 not found in repository docker.io/library/logstash
```

**Comment by tianon** [comment]
Should be up now. :+1:
