### ISSUE TITLE
Plugin installation issue

### ISSUE THREAD

**Issue by lliknart** [docker-library/logstash#55]
Hi,

I have an issue with the logstash 2.3.4-1 version used with user namespace (docker) and some plugins:

Hereafter the issue:

```
# docker run -it --rm repo/logstash:2 logstash -e 'input {stdin {}} output {stdout{}}'
Bundler::InstallError: There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/opt/logstash/Gemfile.jruby-1.9.lock
    lock at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:255
    lock at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:34
   setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:44
   setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
  setup! at /opt/logstash/lib/bootstrap/bundler.rb:64
  (root) at /opt/logstash/lib/bootstrap/environment.rb:65
```

The Dockerfile used:

```
from logstash:2
VOLUME ["/config-dir"]
RUN apt-get update && apt-get install -y libzmq3-dev && \
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
RUN /opt/logstash/bin/logstash-plugin install logstash-input-beats
RUN /opt/logstash/bin/logstash-plugin install logstash-filter-translate
```

When I use:
- Logstash official Dockerfile (logstash:2) + user namespace for docker : OK
- The above Dockerfile without user namespace for docker = OK
- The above Dockerfile + user namespace for docker = KO (issue)

The issue was not present with the Logstash previous version (2.3.3)

Thank you

**Comment by yosifkit** [comment]
PR https://github.com/docker-library/logstash/pull/51 has the only changes between `2.3.3` and `2.3.4`.

Though I am confused by the error, because I don't see ruby and bundler installed in the image.

**Comment by tianon** [comment]
Just tested with user namespaces (using your exact `Dockerfile` listed above) on a completely fresh and empty Docker instance and can't seem to reproduce -- have you tried deleting all the related images (and potential cache layers) and starting fresh to ensure one of the layers didn't get corrupted somehow?

**Comment by lliknart** [comment]
Hi,

I stopped docker engine, removed all images, containers, everything...

```
# service docker stop
# docker volume rm $(docker volume ls -q)
# docker rmi $(docker images -q)
```

I also removed some data:

```
# rm -rf /var/lib/docker/999.999/aufs/*
etc..
```

Below, the daemon.json file

```
# cat /etc/docker/daemon.json:
{
  "userns-remap": "user-test"
}

```

The user "user-test" is a system user created with:

```
# useradd --system user-test
# id user-test
uid=999(user-test) gid=999(user-test) groups=999(user-test),998(docker)

```

The following line has been added in /etc/subuid and /etc/subgid:
`user-test:999:1`

Same issue occured:

```
# docker run -it --rm repo/logstash:2 logstash -e 'input {stdin {}} output {stdout{}}'
Bundler::InstallError: There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/opt/logstash/Gemfile.jruby-1.9.lock
    lock at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/definition.rb:255
    lock at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/environment.rb:34
   setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:44
   setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
  setup! at /opt/logstash/lib/bootstrap/bundler.rb:64
  (root) at /opt/logstash/lib/bootstrap/environment.rb:65
```

The file has the same rights between the old and the new version:

```
# ls -la /var/lib/docker/999.999/aufs/diff/cb6b52383ffb3915f267f6d506211dfb97bfb5d65ee27d54d723f46a8d0753c7/opt/logstash/Gemfile.jruby-1.9.lock
-rw-rw-r-- 1 user-test user-test 21685 Apr 26 16:35 /var/lib/docker/999.999/aufs/diff/cb6b52383ffb3915f267f6d506211dfb97bfb5d65ee27d54d723f46a8d0753c7/opt/logstash/Gemfile.jruby-1.9.lock
```

```
# ls -la /var/lib/docker/999.999/aufs/diff/b9c8043743c4aa85646b2d116b3a7e6bff50d17f00a7955d133e0a1dbc8deb87/opt/logstash/Gemfile.jruby-1.9.lock
-rw-rw-r-- 1 user-test user-test 21901 Jul 19 15:57 /var/lib/docker/999.999/aufs/diff/b9c8043743c4aa85646b2d116b3a7e6bff50d17f00a7955d133e0a1dbc8deb87/opt/logstash/Gemfile.jruby-1.9.lock
```

Listed below, the docker and OS version:

```
# docker --version
Docker version 1.11.2, build b9f10c9

# uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

I have the same installation on 3 systems and the same issue occured after image update.

I tested again with the official image and it works:

```
# docker run -it --rm logstash:2 logstash -e 'input {stdin {}} output {stdout{}}'
Settings: Default pipeline workers: 12
Pipeline main started
```

**Comment by tianon** [comment]
Interesting -- I wonder if it has to do with the fact that user `999` inside the image is `logstash`.  I _think_ user namespaces will obscure that user from being available if that's the user remapped for `root` (which is why Ubuntu's default uses `165536` so there's significantly less chance of overlap).

**Comment by lliknart** [comment]
Hi again,

After having modified the Dockerfile, it works fine.

Dockerfile KO:

```
from logstash:2
VOLUME ["/config-dir"]
RUN apt-get update && apt-get install -y libzmq3-dev && \
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
RUN /opt/logstash/bin/logstash-plugin install logstash-input-beats
RUN /opt/logstash/bin/logstash-plugin install logstash-filter-translate
```

Dockerfile OK:

```
from logstash:2
VOLUME ["/config-dir"]
RUN apt-get update && apt-get install -y libzmq3-dev && \
    rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
RUN /opt/logstash/bin/logstash-plugin install logstash-filter-translate
RUN /opt/logstash/bin/logstash-plugin install logstash-input-beats
```

Yes... I just installed the translate plugin before the beats plugin..
I reproduced the issue many times.

As suggested by a colleague, the file `Gemfile.jruby-1.9.lock` is maybe still locked after beats plugin installation. This lock could cause the issue. (?)
However, if it is the cause, I don't understand why:
- it works fine for you with the first Dockerfile
- it works fine (for me) with the first Dockerfile but without using user namespaces

I rename and close the issue.
