### ISSUE TITLE
Cannot load translate dictionary via docker volume

### ISSUE THREAD

**Issue by orweinberger** [docker-library/logstash#60]
I'm running Logstash 2.4 with the v3.0.0 of the logstash-filter-translate. I have the following configuration:

```
filter {
  translate {
    dictionary_path => "/config/ip_to_plugin.yml"
    field => "host"
    destination => "plugin"
  }
}
```

In my docker run command, I map the volume /my-config-dir:/config which has the ip_to_plugin.yml file and it is fully accessible to the logstash process.

However, when I try and launch logstash with the above config I get this error:

```
{:timestamp=>"2016-09-14T10:33:21.593000+0000", :message=>"Pipeline aborted due to error", :exception=>"RuntimeError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:273:in `loading_exception'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:235:in `load_dictionary'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:166:in `lock_for_write'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
```

I guess that the translate plugin tries to 'lock' the file somehow? I'm not sure how to resolve this.

Also referenced here: logstash-plugins/logstash-filter-translate#36

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
