### ISSUE TITLE
How to determine whether logstash is running or not on my docker container?

### ISSUE THREAD

**Issue by neddogg** [docker-library/logstash#61]
Hi Everybody,

I very sorry if my question is stupid. But this what I have done. I did a 
docker run -it --rm logstash -e 'input { stdin { } } output { stdout { } }'
and everything went on very well.
I then did a 
docker ps
And I was able to see my docker container up.
I then wanted to validate that logstash was started properly. So I connect to the container with the command
sudo docker exec -i -t ead78cd1d78c /bin/bash
where ead78cd1d78c is the container id.
on its shell, I did a 
# service logstash status

and I had the reponse
logstash is not running.

So I'm little bite confused, have I verified it badly?

Thanks for your help.

**Comment by yosifkit** [comment]
There is no init system in the container, the only thing running is logstash as pid 1. This is a duplicate of #59.  See specifically this comment: https://github.com/docker-library/logstash/issues/59#issuecomment-244454300.  Hopefully that helps!

**Comment by neddogg** [comment]
Thanks @yosifkit. After some google and reading I could understand how it works.
