### ISSUE TITLE
Get the logstash logs of a running logstash container.

### ISSUE THREAD

**Issue by neddogg** [docker-library/logstash#63]
Hi Everyone,

After running an image of logstash, I wanted to monitor its logs but don't know where to find that. This is what I did I connected into the running container with the command,

```
docker exec -i -t containerId /bin/bash
```

I went to the folder **/var/log/logstash** but that folder was empty. I whethering how I can get the logs of the running container.

Any clue please?
Thanks.

**Comment by panmichal** [comment]
Logstash sends logs to `stdout` by default so you can use

```
docker logs -f containerId
```

**Comment by jalberto** [comment]
@panmichal the current docker image (5) is configured to log to file not to stdout.

Is this intentional or a bug?

**Comment by tianon** [comment]
@jalberto that sounds like a bug -- https://github.com/docker-library/logstash/blob/0f53eec1fe093f059f7bc3aa0ee1a429378a4b00/5.0/Dockerfile#L40-L48 :disappointed:

**Comment by tianon** [comment]
Looks like the value got renamed:

``` yaml
path.logs: /var/log/logstash
```

**Comment by tianon** [comment]
https://github.com/docker-library/logstash/pull/67 :+1:

**Comment by jalberto** [comment]
@tianon great! any idea when it will be merged?

**Comment by mi-hol** [comment]
@neddogg @tianon  looks like this could be closed, right?

**Comment by tianon** [comment]
Indeed, thanks @mi-hol!

**Comment by sandeep1-0** [comment]
Is it possible to get the logs of logstash container through mentioning path inside the yml file.
