### ISSUE TITLE
fails to push schema and logs to ES if container launched with the default entrypoint 

### ISSUE THREAD

**Issue by sjeeva** [docker-library/logstash#68]
I ran ELK stack with the official ElasticSearch, LogStash, and Kibana images. I was able to load schema and data to ES using restapi.. However LogStash could not push schema to ES and also it was not reading the loading the log from local file. As a workaround, I solved the issue by overriding the default entrypoint. Perhaps entrypoint script has a bug or I am messing up something. Below is the code snippet from https://github.com/sjeeva/elk

```
  logstash:
    image: logstash:5.0.0
    # NOTE: logstash isn't updating ES with command, might be an entry script bug
    #command: -f /config-dir/apache.conf --log.level debug --config.debug
    entrypoint: logstash -f /etc/logstash/conf.d/logstash.conf 
    volumes:
      # NOTE: currently it is configured to handle just apache logs 
      - ${PWD}/logstash/config/:/etc/logstash/conf.d
      - /var/log/apache2/:/log/
```

**Comment by tianon** [comment]
Do you have any logs from the failing container?  Also, I'm assuming `-f /config-dir/apache.conf` was a typo and you actually meant `-f /etc/logstash/conf.d/logstash.conf` like in the following line?

**Comment by mi-hol** [comment]
@sjeeva did Tianon's comment fix your issue?

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
