### ISSUE TITLE
Remove test files from image

### ISSUE THREAD

**Issue by sybrandy** [docker-library/logstash#77]
Hello,

This may be an odd request, but can any test files be removed from the image or just not installed?  My company requires that all downloads, including images, be virus scanned before we use them on a project.  In the current image, there are some tar file that aren't tar files and that causes the scanner to complain.

Thanks.

**Comment by tianon** [comment]
If they aren't used at runtime, I'm +1 on removing them. :+1:

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
