### ISSUE TITLE
NotImplementedError: stat.st_dev unsupported or native support failed to load

### ISSUE THREAD

**Issue by impanda-cookie** [docker-library/logstash#84]
Using `logstash:alpine` latest version (mac osx 10.12) with custom conf as follows:

```
input {
    file {
        path => "/var/log/nginx/access.log"
        codec => "json"
        tags => ["nginx"]
        type => "elk"
    }
}

filter{
    date {
        match => ["timestamp","yyyy-MM-dd hh:mm:ss"]
    }
}

output{
    stdout{
        codec=>rubydebug
    }
}
```

will throw error but `logstash:latest` work fine. how to fix ?

> NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:214
       nix_inode at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.9.0/lib/filewatch/watch.rb:28
           inode at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.9.0/lib/filewatch/watch.rb:32
           inode at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.9.0/lib/filewatch/watch.rb:106
           watch at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.9.0/lib/filewatch/watch.rb:96
  _discover_file at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch-0.9.0/lib/filewatch/watch.rb:313
            each at org/jruby/RubyArray.java:1613
            each at org/jruby/RubyEnumerator.java:274
  _discover_file at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/filewatch...

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
