### ISSUE TITLE
To let logstash to run as root in docker (managed by marathon)

### ISSUE THREAD

**Issue by zhengkai6** [docker-library/logstash#86]
First I changed the startup.option file, to  let the following config items to be root user:
# user and group id to be invoked as
LS_USER=root
LS_GROUP=root
But it does not take effect.

Then, I changed my marathon json file, to add parameter in docker config, but the runner is also logstash, not changed to root.

logstash     1 36.0  2.8 6103200 460876 ?      Ssl  03:44   1:58 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSIni
root       105  0.0  0.0  22012  2280 ?        Ss   03:47   0:00 /bin/bash
root       127  0.0  0.0  19180  1312 ?        R+   03:49   0:00 ps aux

**Comment by zhengkai6** [comment]
I've already read the doc in 
https://github.com/docker-library/logstash/issues/79
https://github.com/docker-library/elasticsearch/pull/14
https://github.com/docker-library/logstash/issues/11

But they do not solve my problem, and my docker image still runs as logstash in the container.

Could anyone figure this out?
Thanks very much!

**Comment by yosifkit** [comment]
You just need to override the entrypoint and just run logstash directly (the only thing gained by using the entrypoint is the drop down from root, which is what you don't want); so something like this:
```json
{
  "id": "logstash",
  "container": {
    "type": "DOCKER",
    "args": [ "-f", "/path/to/logstash.conf" ],
    "docker": {
      "image": "logstash:5",
      "network": "BRIDGE",
      "parameters": [
        { "key": "entrypoint", "value": "logstash" }
      ]
    }
  }
}
```

**Comment by zhengkai6** [comment]
OK I will try it next time

You are also using mesos framework? Interesting...

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/logstash/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `logstash` image](https://www.elastic.co/guide/en/logstash/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/logstash/logstash:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Logstash via the [elastic/logstash GitHub repository](https://github.com/elastic/logstash) and the Docker image via the [elastic/logstash-docker GitHub repository](https://github.com/elastic/logstash-docker), as well as community support via its [forums](https://discuss.elastic.co/c/logstash).

Thanks!
