### ISSUE TITLE
Provide updateable version tags like latest or 5.2 and a version history

### ISSUE THREAD

**Issue by DMW007** [docker-library/logstash#87]
In the [official Docker hub](https://hub.docker.com/_/logstash/), it's common practice to offer additional tags for major and minor versions of a software. For example on logstash, we've currently the exact version `5.4.1` but also `5.4` and `5`. That's great to control the update behaviour, and avoid the usage of old images, that can cause security issues. 

But you've announced that all images on the Docker hub were moved to  our custom hosted one `docker.elastic.co/logstash/logstash:[version]`. Here it seems that we don't have those tags like the Docker hub, like this example shows:

```
# docker pull docker.elastic.co/logstash/logstash:5.4
Pulling repository docker.elastic.co/logstash/logstash
Error: image logstash/logstash:5.4 not found
```
In genereal, there is no overview, which tags are avaliable like the [tags on Docker hub](https://hub.docker.com/r/library/logstash/tags/). I'm not bascially against this move, like other comments indicate. But I think this is an important feature, that seems to get lost. So in the current state, this step impairs the current situation, instead of improving them - From the view of a user. 

So when you really want to move from Docker hub, please provide different tags and a list of the avaliable ones. The new solution seems confusing and less good documentated than the current one on Docker hub.

**Comment by yosifkit** [comment]
The new images are not controlled by us, but by [Elastic](https://www.elastic.co/) the company.  You'll probably want to file an issue on their repo: https://github.com/elastic/logstash-docker
