### ISSUE TITLE
More generic tags

### ISSUE THREAD

**Issue by thenewguy** [docker-library/logstash#98]
Any chance for more generic tags?  

For example, `:7` to indicate that I want the latest of version `7.x.y` or `:7.6` to indicate that I would like the latest version of `7.6.x`

**Comment by yosifkit** [comment]
> Note: Pulling an image requires using a specific version number tag. The latest tag is not supported.
>
> [Docker Hub readme](https://github.com/docker-library/docs/tree/be7bfcaa2c943298ddb75da86dacdfe42217f6de/logstash#how-to-use-this-image)

Unfortunately no.  We only review and mirror what Elastic Inc. publishes. You'd need to file an issue with Elastic Inc.

> Where to file issues and PRs
> - [Issues](https://github.com/elastic/logstash/issues)
>
> \- https://github.com/elastic/dockerfiles/tree/v7.6.2#where-to-file-issues-and-prs-2
